sudo: required
language: node_js
node_js:
    - '6'
services:
    - docker
addons:
  ssh_known_hosts: 207.154.222.71

before_install:
    - openssl aes-256-cbc -K $encrypted_06f26ffc899b_key -iv $encrypted_06f26ffc899b_iv -in travis_rsa.enc -out travis_rsa -d
    - docker login -u $DOCKER_HUB_LOGIN -p $DOCKER_HUB_PASSWORD hub.docker.com
    - docker build -t apolyansky/docker-uptime:latest .
    - docker push apolyansky/docker-uptime:latest

deploy:
  skip_cleanup: true
  provider: script
  script: .travis/deploy.sh
  on:
    all_branches: true
