sudo: required
language: node_js
node_js:
    - '6'
services:
    - docker
addons:
  ssh_known_hosts: 207.154.222.71

before_install:
    - rvm install 2.2.2
    - openssl aes-256-cbc -K $encrypted_06f26ffc899b_key -iv $encrypted_06f26ffc899b_iv -in travis_rsa.enc -out travis_rsa -d
    - chmod 600 ~/.ssh/travis_rsa
script:
    - docker-compose up --build
deploy:
  skip_cleanup: true
  provider: script
  script: .travis/deploy.sh
  on:
    all_branches: true
